<script>
	require([
		'jquery',
		'jquery/validate'
	], function(jQuery) {

		function tezusAutocompleteFillData(json) {
			// Country
			var country = jQuery("[name=country_id]");
			country.val('BR');

			// Street
			var customStreet = "<?php echo $this->getCustomStreet(); ?>";
			var street = jQuery("#".concat(customStreet));
			street.val(json.street);

			// Quarter
			var customQuarter = "<?php echo $this->getCustomQuarter(); ?>";
			var street = jQuery("#".concat(customQuarter));
			street.val(json.neighborhood);

			// City
			var customCity = "<?php echo $this->getCustomCity(); ?>";
			var city = jQuery("#".concat(customCity));
			city.val(json.city);

			// State
			var customState = "<?php echo $this->getCustomState(); ?>";
			var state = jQuery("#".concat(customState));
			state.val(tezusAutocompleteUF[json.state]);

		}

		// DYNAMIC
		jQuery(document).ready(function() {
			var interval;

			function tezusAutocompleteDoEvents() {
				jQuery("[name=postcode]").blur(function() {
					var value = jQuery(this).val();
					jQuery.ajax({
						data: {
							form_key: window.FORM_KEY
						},
						url: TEZUS_AUTOCOMPLETE_URL + value,
						showLoader: true,

						success: function(data) {
							if (!data.city) return;
							tezusAutocompleteFillData(data);
						},
					});

				});

				clearInterval(interval);
			}

			var time = "<?php echo $this->getLoadPageTime(); ?>";
			interval = setInterval(tezusAutocompleteDoEvents, time);


		});

	});
</script>