<script>
	var tezusAutocompleteUF = {
		'AC': '485',
		'AL': '486',
		'AP': '487',
		'AM': '488',
		'BA': '489',
		'CE': '490',
		'DF': '511',
		'ES': '491',
		'GO': '492',
		'MA': '493',
		'MT': '494',
		'MS': '495',
		'MG': '496',
		'PA': '497',
		'PB': '498',
		'PR': '499',
		'PE': '500',
		'PI': '501',
		'RJ': '502',
		'RN': '503',
		'RS': '504',
		'RO': '505',
		'RR': '506',
		'SC': '507',
		'SP': '508',
		'SE': '509',
		'TO': '510'
	}

	var TEZUS_AUTOCOMPLETE_URL = "<?php echo $this->getAjaxUrl(); ?>";
</script>